language: generic
sudo:  required
services:
    - docker

before_install:
  - docker build -t orange29/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true orange29/docker-react npm run test